#!/bin/sh

OS=`uname`
BASE=`dirname $0`;
cd $BASE;

if [ $OS = "Linux" ]; then
	CLASS=org.jzuul.gdk.Main
	JAVA=`which java`
	if [ -d lib/swt_linux_motif ]; then
		LIBRARY_PATH=lib/swt_linux_motif
	fi
	if [ -d lib/swt_linux ]; then
		LIBRARY_PATH=lib/swt_linux
	fi
	if [ -d /usr/lib/mozilla ]; then
		export MOZILLA_FIVE_HOME=/usr/lib/mozilla
	fi
	if [ -d /usr/local/mozilla ]; then
		export MOZILLA_FIVE_HOME=/usr/local/mozilla
	fi
fi

if [ $OS = "Darwin" ]; then
	CLASS=org.jzuul.gdk.Main
	LIBRARY_PATH=lib/swt_macosx_carbon
	JAVA=$LIBRARY_PATH/java_swt
	chmod ugo+x $JAVA 1> /dev/null 2>&1
fi

CLASSPATH=lib/xerces.jar:lib/jdom.jar:$LIBRARY_PATH/swt.jar:$LIBRARY_PATH/swt-mozilla.jar:$LIBRARY_PATH/swt-pi.jar:./

$JAVA -cp $CLASSPATH -Djava.library.path=$LIBRARY_PATH $CLASS $@
